// Juice library — 50 natural recipes, English-only, NO photos.
// Organized by goal. Used on the /sucos route (list + filters).
// The "Sacred Juice" remains the featured ritual (route /suco-sagrado).

export type SucoCat = "desinflamar" | "energia" | "sono" | "detox" | "imunidade";

export interface Suco {
  id: string;
  cat: SucoCat;
  nome: string;
  beneficio: string;
  ingredientes: string[];
  preparo: string[];
}

export const sucoCats: { id: SucoCat; label: string; emoji: string }[] = [
  { id: "desinflamar", label: "De-Bloat", emoji: "🌿" },
  { id: "energia", label: "Energy", emoji: "☀️" },
  { id: "sono", label: "Sleep & Calm", emoji: "🌙" },
  { id: "detox", label: "Detox & Liver", emoji: "💧" },
  { id: "imunidade", label: "Immunity", emoji: "🛡️" },
];

// Standard reusable steps (blender / infusion).
const BLEND = [
  "Blend all the ingredients with 200 ml (¾ cup) of cold water until smooth.",
  "Strain if you prefer and serve immediately, ideally on an empty stomach.",
];
const TEA = [
  "Steep in hot water and let cool slightly for 5 minutes.",
  "Stir in the honey and lemon.",
  "Drink warm, slowly, before bed.",
];

export const sucos: Suco[] = [
  // ───────────────────────── DE-BLOAT ─────────────────────────
  {
    id: "verde-do-jordao",
    cat: "desinflamar",
    nome: "Jordan Green",
    beneficio: "Reduces bloating and calms the gut within the first week.",
    ingredientes: ["1 kale leaf", "1 slice of pineapple", "1 slice of fresh ginger", "Juice of 1 lemon", "Mint to taste"],
    preparo: BLEND,
  },
  {
    id: "dourado-anti-inflamatorio",
    cat: "desinflamar",
    nome: "Golden Anti-Inflammatory",
    beneficio: "Turmeric and ginger lower inflammation throughout the whole body.",
    ingredientes: ["1 carrot", "Juice of 2 oranges", "1 teaspoon turmeric", "1 slice of fresh ginger", "1 pinch of black pepper"],
    preparo: BLEND,
  },
  {
    id: "abacaxi-hortela",
    cat: "desinflamar",
    nome: "Pineapple Mint",
    beneficio: "The bromelain in pineapple helps de-bloat and digest.",
    ingredientes: ["2 slices of pineapple", "Mint to taste", "1 slice of fresh ginger", "200 ml (¾ cup) coconut water"],
    preparo: BLEND,
  },
  {
    id: "curcuma-limao",
    cat: "desinflamar",
    nome: "Turmeric & Lemon",
    beneficio: "A morning shot that wakes up the liver and fights inflammation.",
    ingredientes: ["Juice of 1 lemon", "1 teaspoon turmeric", "1 teaspoon honey", "1 pinch of black pepper", "200 ml (¾ cup) warm water"],
    preparo: ["Stir everything into the warm water until dissolved.", "Drink on an empty stomach, all at once."],
  },
  {
    id: "pepino-refrescante",
    cat: "desinflamar",
    nome: "Cooling Cucumber",
    beneficio: "Deeply hydrates and reduces water retention.",
    ingredientes: ["½ cucumber", "Juice of 1 lemon", "Mint to taste", "1 green apple"],
    preparo: BLEND,
  },
  {
    id: "gengibre-maca",
    cat: "desinflamar",
    nome: "Ginger & Apple",
    beneficio: "Warms, de-bloats, and regulates digestion.",
    ingredientes: ["1 apple", "1 slice of fresh ginger", "Juice of ½ lemon", "Cinnamon to taste"],
    preparo: BLEND,
  },
  {
    id: "beterraba-profunda",
    cat: "desinflamar",
    nome: "Deep Beet",
    beneficio: "A powerful antioxidant that improves circulation.",
    ingredientes: ["½ beet", "Juice of 2 oranges", "1 slice of fresh ginger"],
    preparo: BLEND,
  },
  {
    id: "cenoura-laranja",
    cat: "desinflamar",
    nome: "Carrot & Orange",
    beneficio: "Beta-carotene and vitamin C for skin and immunity.",
    ingredientes: ["1 carrot", "Juice of 2 oranges", "1 pinch of turmeric"],
    preparo: BLEND,
  },
  {
    id: "couve-suave",
    cat: "desinflamar",
    nome: "Gentle Kale",
    beneficio: "Chlorophyll and fiber that feed the good gut bacteria.",
    ingredientes: ["1 kale leaf", "1 apple", "Juice of 1 lemon", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "melancia-gengibre",
    cat: "desinflamar",
    nome: "Watermelon & Ginger",
    beneficio: "A natural diuretic that de-bloats without heaviness.",
    ingredientes: ["2 slices of watermelon", "1 slice of fresh ginger", "Mint to taste"],
    preparo: BLEND,
  },

  // ───────────────────────── ENERGY ─────────────────────────
  {
    id: "sol-da-manha",
    cat: "energia",
    nome: "Morning Sun",
    beneficio: "Clean energy to start the day without coffee.",
    ingredientes: ["Juice of 2 oranges", "1 carrot", "1 apple", "1 slice of fresh ginger"],
    preparo: BLEND,
  },
  {
    id: "verde-vital",
    cat: "energia",
    nome: "Vital Green",
    beneficio: "Iron and potassium that sustain your energy all day.",
    ingredientes: ["1 handful of spinach", "1 banana", "1 apple", "200 ml (¾ cup) coconut water"],
    preparo: BLEND,
  },
  {
    id: "banana-aveia",
    cat: "energia",
    nome: "Banana & Oats",
    beneficio: "Long-lasting fullness and steady energy, no sugar spike.",
    ingredientes: ["1 banana", "2 tablespoons oats", "200 ml (¾ cup) plant milk", "Cinnamon to taste"],
    preparo: ["Blend everything into a smooth cream.", "Serve right away, dusted with cinnamon."],
  },
  {
    id: "beterraba-energetica",
    cat: "energia",
    nome: "Energizing Beet",
    beneficio: "Boosts stamina and physical drive.",
    ingredientes: ["½ beet", "1 apple", "Juice of 1 orange"],
    preparo: BLEND,
  },
  {
    id: "abacaxi-tropical",
    cat: "energia",
    nome: "Tropical Pineapple",
    beneficio: "Refreshing and full of vitamin C to lift your spirits.",
    ingredientes: ["2 slices of pineapple", "Juice of 1 orange", "Mint to taste"],
    preparo: BLEND,
  },
  {
    id: "maca-canela",
    cat: "energia",
    nome: "Apple & Cinnamon",
    beneficio: "Steadies blood sugar and gives calm, even energy.",
    ingredientes: ["2 apples", "1 teaspoon cinnamon", "Juice of ½ lemon", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "manga-dourada",
    cat: "energia",
    nome: "Golden Mango",
    beneficio: "Natural sweetness that recharges you after exercise.",
    ingredientes: ["½ mango", "Juice of 1 orange", "1 pinch of turmeric"],
    preparo: BLEND,
  },
  {
    id: "uva-limao",
    cat: "energia",
    nome: "Grape & Lemon",
    beneficio: "Antioxidants that renew your cells' energy.",
    ingredientes: ["1 handful of purple grapes", "Juice of 1 lemon", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "cenoura-power",
    cat: "energia",
    nome: "Carrot Power",
    beneficio: "Vitamin A and energy for morning focus.",
    ingredientes: ["2 carrots", "1 apple", "1 slice of fresh ginger", "Juice of ½ lemon"],
    preparo: BLEND,
  },
  {
    id: "verde-despertar",
    cat: "energia",
    nome: "Green Awakening",
    beneficio: "Replaces coffee with light, clear energy.",
    ingredientes: ["1 green apple", "1 handful of spinach", "Juice of 1 lemon", "1 slice of fresh ginger"],
    preparo: BLEND,
  },

  // ───────────────────────── SLEEP & CALM ─────────────────────────
  {
    id: "calmaria-da-noite",
    cat: "sono",
    nome: "Evening Calm",
    beneficio: "Relaxes the body and prepares you for deep sleep.",
    ingredientes: ["1 apple", "A few lettuce leaves", "Mint to taste", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "camomila-mel",
    cat: "sono",
    nome: "Chamomile & Honey",
    beneficio: "The classic infusion that quiets the mind before bed.",
    ingredientes: ["1 chamomile tea bag", "1 teaspoon honey", "Juice of ½ lemon", "250 ml (1 cup) hot water"],
    preparo: TEA,
  },
  {
    id: "maracuja-sereno",
    cat: "sono",
    nome: "Serene Passion Fruit",
    beneficio: "A natural calmer that eases nighttime anxiety.",
    ingredientes: ["Pulp of 1 passion fruit", "1 teaspoon honey", "250 ml (1 cup) water"],
    preparo: BLEND,
  },
  {
    id: "banana-maca-noturna",
    cat: "sono",
    nome: "Nighttime Banana & Apple",
    beneficio: "Magnesium and tryptophan that help you unwind.",
    ingredientes: ["1 banana", "1 apple", "Cinnamon to taste", "200 ml (¾ cup) plant milk"],
    preparo: BLEND,
  },
  {
    id: "alface-limao",
    cat: "sono",
    nome: "Lettuce & Lemon",
    beneficio: "Lettuce has a gentle, natural calming effect.",
    ingredientes: ["A few lettuce leaves", "Juice of 1 lemon", "1 apple", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "cereja-tranquila",
    cat: "sono",
    nome: "Tranquil Cherry",
    beneficio: "A natural source of melatonin for sleep.",
    ingredientes: ["1 handful of pitted cherries", "Juice of ½ lemon", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "erva-doce-calmante",
    cat: "sono",
    nome: "Calming Fennel",
    beneficio: "Settles the stomach and the body at day's end.",
    ingredientes: ["1 tablespoon fennel seeds", "1 teaspoon honey", "250 ml (1 cup) hot water"],
    preparo: TEA,
  },
  {
    id: "pera-suave",
    cat: "sono",
    nome: "Gentle Pear",
    beneficio: "Lightly sweet, and won't sit heavy before bed.",
    ingredientes: ["1 pear", "A few lettuce leaves", "200 ml (¾ cup) water", "Mint to taste"],
    preparo: BLEND,
  },
  {
    id: "mel-hortela-noite",
    cat: "sono",
    nome: "Honey & Mint",
    beneficio: "A warm drink that soothes the throat and the mind.",
    ingredientes: ["1 teaspoon honey", "Fresh mint", "Juice of ½ lemon", "250 ml (1 cup) warm water"],
    preparo: TEA,
  },
  {
    id: "lavanda-doce",
    cat: "sono",
    nome: "Sweet Lavender",
    beneficio: "An aroma and infusion that invite relaxation.",
    ingredientes: ["1 teaspoon culinary lavender", "1 teaspoon honey", "250 ml (1 cup) hot water"],
    preparo: TEA,
  },

  // ───────────────────────── DETOX & LIVER ─────────────────────────
  {
    id: "detox-verde",
    cat: "detox",
    nome: "Green Detox",
    beneficio: "Cleanses the system and brings morning lightness.",
    ingredientes: ["1 kale leaf", "½ cucumber", "Juice of 1 lemon", "1 slice of fresh ginger", "Parsley to taste"],
    preparo: BLEND,
  },
  {
    id: "limao-salsinha",
    cat: "detox",
    nome: "Lemon & Parsley",
    beneficio: "A potent diuretic that helps the kidneys cleanse.",
    ingredientes: ["Juice of 1 lemon", "1 handful of parsley", "1 slice of fresh ginger", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "beterraba-purificadora",
    cat: "detox",
    nome: "Purifying Beet",
    beneficio: "Supports the liver and renews the blood.",
    ingredientes: ["½ beet", "1 carrot", "Juice of 1 lemon", "1 slice of fresh ginger"],
    preparo: BLEND,
  },
  {
    id: "clorofila-pura",
    cat: "detox",
    nome: "Pure Chlorophyll",
    beneficio: "Concentrated greens that oxygenate and detoxify.",
    ingredientes: ["1 kale leaf", "1 handful of spinach", "½ cucumber", "Juice of 1 lemon"],
    preparo: BLEND,
  },
  {
    id: "maca-verde-detox",
    cat: "detox",
    nome: "Green Apple Detox",
    beneficio: "Refreshes and flushes out excess toxins.",
    ingredientes: ["1 green apple", "½ cucumber", "Mint to taste", "Juice of 1 lemon"],
    preparo: BLEND,
  },
  {
    id: "gengibre-curcuma-detox",
    cat: "detox",
    nome: "Ginger & Turmeric Detox",
    beneficio: "A warm shot that fires up the metabolism and cleanses.",
    ingredientes: ["1 slice of fresh ginger", "1 teaspoon turmeric", "Juice of 1 lemon", "200 ml (¾ cup) warm water"],
    preparo: ["Stir everything into the warm water.", "Drink on an empty stomach, all at once."],
  },
  {
    id: "abacaxi-hortela-detox",
    cat: "detox",
    nome: "Pineapple & Mint Detox",
    beneficio: "De-bloats and helps flush out what your body doesn't need.",
    ingredientes: ["2 slices of pineapple", "Mint to taste", "½ cucumber", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
  {
    id: "limpeza-do-jejum",
    cat: "detox",
    nome: "Morning Cleanse",
    beneficio: "The first sip of the day that wakes up your digestive system.",
    ingredientes: ["Juice of 1 lemon", "1 slice of fresh ginger", "1 pinch of cayenne pepper", "250 ml (1 cup) warm water"],
    preparo: ["Stir everything into the warm water.", "Drink on an empty stomach, 20 minutes before breakfast."],
  },
  {
    id: "couve-abacaxi",
    cat: "detox",
    nome: "Kale & Pineapple",
    beneficio: "The green classic that cleanses and de-bloats at once.",
    ingredientes: ["1 kale leaf", "2 slices of pineapple", "Juice of 1 lemon", "1 slice of fresh ginger"],
    preparo: BLEND,
  },
  {
    id: "aipo-verde",
    cat: "detox",
    nome: "Green Celery",
    beneficio: "Hydrates, alkalizes, and reduces water retention.",
    ingredientes: ["2 celery stalks", "1 green apple", "Juice of 1 lemon", "½ cucumber"],
    preparo: BLEND,
  },

  // ───────────────────────── IMMUNITY ─────────────────────────
  {
    id: "escudo-de-citricos",
    cat: "imunidade",
    nome: "Citrus Shield",
    beneficio: "A vitamin C bomb to armor the body.",
    ingredientes: ["Juice of 1 orange", "Juice of 1 lemon", "1 handful of acerola cherries", "1 teaspoon honey"],
    preparo: BLEND,
  },
  {
    id: "acerola-laranja",
    cat: "imunidade",
    nome: "Acerola & Orange",
    beneficio: "One of nature's richest sources of vitamin C.",
    ingredientes: ["1 handful of acerola cherries", "Juice of 2 oranges", "1 teaspoon honey"],
    preparo: BLEND,
  },
  {
    id: "gengibre-mel-imune",
    cat: "imunidade",
    nome: "Ginger & Honey",
    beneficio: "Warms and protects the throat on cold days.",
    ingredientes: ["1 slice of fresh ginger", "1 teaspoon honey", "Juice of 1 lemon", "250 ml (1 cup) warm water"],
    preparo: TEA,
  },
  {
    id: "laranja-curcuma-imune",
    cat: "imunidade",
    nome: "Immune Orange & Turmeric",
    beneficio: "An anti-inflammatory duo that strengthens your defenses.",
    ingredientes: ["Juice of 2 oranges", "1 teaspoon turmeric", "1 teaspoon honey", "1 pinch of black pepper"],
    preparo: BLEND,
  },
  {
    id: "limao-alho",
    cat: "imunidade",
    nome: "Protective Lemon & Garlic",
    beneficio: "A strong natural antibiotic for the first signs of a cold.",
    ingredientes: ["Juice of 1 lemon", "1 small garlic clove", "1 teaspoon honey", "250 ml (1 cup) warm water"],
    preparo: ["Crush the garlic and stir everything into the warm water.", "Let rest 2 minutes and drink."],
  },
  {
    id: "morango-acerola",
    cat: "imunidade",
    nome: "Strawberry & Acerola",
    beneficio: "Antioxidants and vitamin C in a single glass.",
    ingredientes: ["1 handful of strawberries", "1 handful of acerola cherries", "Juice of 1 orange"],
    preparo: BLEND,
  },
  {
    id: "goiaba-vitamina",
    cat: "imunidade",
    nome: "Vitamin Guava",
    beneficio: "Guava has even more vitamin C than oranges.",
    ingredientes: ["1 guava", "Juice of 1 orange", "Juice of ½ lemon"],
    preparo: BLEND,
  },
  {
    id: "roma-protetora",
    cat: "imunidade",
    nome: "Protective Pomegranate",
    beneficio: "A biblical fruit rich in antioxidants that defend the body.",
    ingredientes: ["Seeds of 1 pomegranate", "Juice of 1 orange", "Juice of ½ lemon"],
    preparo: BLEND,
  },
  {
    id: "kiwi-laranja",
    cat: "imunidade",
    nome: "Kiwi & Orange",
    beneficio: "Double vitamin C that boosts your defenses.",
    ingredientes: ["1 kiwi", "Juice of 2 oranges", "1 teaspoon honey"],
    preparo: BLEND,
  },
  {
    id: "caju-mel",
    cat: "imunidade",
    nome: "Cashew Fruit & Honey",
    beneficio: "Cashew fruit juice is extremely rich in vitamin C.",
    ingredientes: ["2 cashew fruits", "Juice of 1 orange", "1 teaspoon honey", "200 ml (¾ cup) water"],
    preparo: BLEND,
  },
];
